# Site settings
title: "ECE 4960: Fast Robots | Natalie Morris   "
author:
  name: Natalie Morris
  email: nhm38@cornell.edu
description: "Coursework for ECE 4960: Fast Robots."
permalink: pretty

# Theme
remote_theme: chrisrhymes/bulma-clean-theme
